server:
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
